/**
 * The FACT-SHEET parser, against the shape the generator actually writes.
 *
 * The fixture below is copied from `taskly-brain/00-brain/FACT-SHEET.md` —
 * marker, header, separator, a constant row, a `↳` commentary row and a row
 * whose value is a sentence — because the failure that matters here is silent:
 * a parser that quietly returns fewer facts than the sheet holds removes checks
 * nobody decided to remove.
 */
import { describe, expect, it } from 'vitest';

import { FACT_SHEET_ENV, factKey, loadFactSheet, parseFactSheet } from './fact-sheet.js';

const SHEET = `---
type: reference
---

# Fact sheet

Prose above the marker mentions **99%** and must not be read.

<!-- BRAIN:FACTS:START — generated by scripts/brain-facts.mjs — DO NOT EDIT BY HAND -->

### Marketplace money (the live engine)

| Fact | Value (from code) | Defined in | Quoted by |
|---|---|---|---|
| Tasker-side commission | **20%** | \`lib/marketplace/fees.ts\` | [X](x.md) |
| ↳ | HST-inclusive. Tasker keeps the rest of the deal (~80%). | | |
| Poster platform fee — floor | **$2.99** | \`lib/marketplace/fees.ts\` | [X](x.md) |
| Referral reward (each side) | **$10.00** | \`lib/booking/referralCredits.ts\` | [X](x.md) |

<!-- BRAIN:FACTS:END -->

Prose below the marker mentions **77%** and must not be read.
`;

describe('factKey', () => {
  it('strips the sheet’s prose punctuation so the subject words are words', () => {
    expect(factKey('Poster platform fee — rate')).toBe('poster_platform_fee_rate');
    expect(factKey('HST rate (embedded in Taskly’s take)')).toBe('hst_rate');
    expect(factKey('Referral reward (each side)')).toBe('referral_reward');
  });
});

describe('parseFactSheet', () => {
  const facts = parseFactSheet(SHEET);

  it('reads the constants, with the code path that defines each', () => {
    expect(facts['tasker_side_commission']).toEqual({
      value: '20%',
      source: 'lib/marketplace/fees.ts',
    });
    expect(facts['poster_platform_fee_floor']?.value).toBe('$2.99');
    // The parenthetical is dropped: it is prose, and "(each side)" would
    // contribute "side" as a subject word, which matches almost anything.
    expect(facts['referral_reward']?.value).toBe('$10.00');
  });

  it('reads nothing outside the markers', () => {
    const values = Object.values(facts).map((f) => f.value);
    expect(values).not.toContain('99%');
    expect(values).not.toContain('77%');
  });

  it('skips the header, the separator and the ↳ commentary rows', () => {
    expect(Object.keys(facts)).toHaveLength(3);
    expect(Object.keys(facts)).not.toContain('fact');
  });

  it('skips a row whose value is a sentence rather than a constant', () => {
    // `checkFactSheet` compares numeric tokens by unit; a sentence contributes
    // no constant and only adds subject words that can produce a false
    // contradiction.
    for (const f of Object.values(facts)) expect(f.value).toMatch(/^[$]?[\d.,]+%?$/);
  });

  it('refuses a file that is not the generated sheet', () => {
    expect(() => parseFactSheet('# just a doc\n\n| a | b |\n')).toThrow(/BRAIN:FACTS markers/);
  });

  it('refuses a sheet that parses to nothing rather than verifying against nothing', () => {
    expect(() =>
      parseFactSheet(`${'<!-- BRAIN:FACTS:START -->'}\n| Fact | Value |\n${'<!-- BRAIN:FACTS:END -->'}`),
    ).toThrow(/zero constants/);
  });
});

describe('loadFactSheet', () => {
  it('refuses to run with the path unset instead of returning an empty sheet', () => {
    expect(() => loadFactSheet({})).toThrow(new RegExp(FACT_SHEET_ENV));
  });
});
