/**
 * The FACT-SHEET, read rather than copied.
 *
 * `verifyAdversarially` takes a `FactSheet` and its own comment is emphatic
 * about where one may come from: "Injected, never copied into this module — a
 * second copy is a second thing that can go stale, and the whole point of the
 * sheet is that it cannot." AGENTS.md rule 7 says the same thing from the other
 * side: money and flags come from the generated sheet, never from prose.
 *
 * So this parses the real file. `taskly-brain/00-brain/FACT-SHEET.md` in the
 * marketplace repo is generated by `npm run brain:facts` from the constants in
 * the code, and CI fails there when it goes stale — which makes it the only
 * artefact in either repo that is both machine-written and human-readable. It
 * is a markdown table between two markers, and parsing it is a dozen lines.
 *
 * FAIL CLOSED, LOUDLY. An unreadable or unconfigured sheet returns no facts,
 * and a verifier handed no facts silently skips the constants check while
 * reporting the same `survives` it would have reported after running it. That
 * is a gate that has been removed without anyone deciding to remove it, so
 * `loadFactSheet` throws instead, and the caller decides — deliberately —
 * whether to proceed without it.
 *
 * WHAT THIS DELIBERATELY DOES NOT DO: scope facts to Taskly. `checkFactSheet`
 * matches a sentence if ANY of a fact's subject words appear in it, which is
 * right for a claim about our own numbers and wrong for a claim about someone
 * else's — "Handy's commission is 15%" names a commission and a percentage, and
 * would be refuted for disagreeing with OUR 20%. The scope rule therefore lives
 * at the call site, in `verifier.ts`, where the claim's subject is known.
 */
import { readFileSync } from 'node:fs';

import type { FactSheet } from '@tmos/reason';

/** The generator's markers. Text outside them is prose and is not read. */
const START = '<!-- BRAIN:FACTS:START';
const END = '<!-- BRAIN:FACTS:END';

/** `| Fact | **$2.99** | `lib/x.ts` | … |` — name, value, where it is defined. */
interface Row {
  readonly name: string;
  readonly value: string;
  readonly source: string;
}

const cells = (line: string): string[] =>
  line
    .replace(/^\s*\|/, '')
    .replace(/\|\s*$/, '')
    .split('|')
    .map((c) => c.trim());

const unwrap = (cell: string): string => cell.replace(/\*\*/g, '').replace(/`/g, '').trim();

/**
 * `Poster platform fee — rate` → `poster_platform_fee_rate`.
 *
 * The key is what `checkFactSheet` reports and what its default subject words
 * are split from, so the em-dashes and parentheses the sheet uses for prose
 * have to go — `(the live engine)` as a subject word would match nothing.
 */
export function factKey(name: string): string {
  return name
    .toLowerCase()
    .replace(/\([^)]*\)/g, ' ')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

/**
 * A value worth checking is one `checkFactSheet` can compare: it extracts
 * numeric tokens and matches them by unit, so a row whose value is a sentence
 * ("HST-inclusive…") contributes nothing and would only add subject words that
 * can produce a false contradiction.
 */
const isConstant = (value: string): boolean => /^[$]?\d[\d,]*(?:\.\d+)?%?$/.test(value);

export function parseFactSheet(markdown: string): FactSheet {
  const from = markdown.indexOf(START);
  const to = markdown.indexOf(END);
  if (from === -1 || to === -1 || to < from) {
    throw new Error(
      'FACT-SHEET has no BRAIN:FACTS markers — either the file is not the generated sheet, ' +
        'or the generator changed shape and this parser has to be re-read against it',
    );
  }

  const out: Record<string, { value: string; source: string }> = {};
  for (const line of markdown.slice(from, to).split('\n')) {
    if (!line.trimStart().startsWith('|')) continue;
    const c = cells(line);
    if (c.length < 3) continue;

    const name = unwrap(c[0] ?? '');
    // Header, separator, and the `↳` continuation rows that carry commentary
    // rather than a constant.
    if (name === '' || name === 'Fact' || name.startsWith('↳') || /^:?-+:?$/.test(name)) continue;

    const row: Row = { name, value: unwrap(c[1] ?? ''), source: unwrap(c[2] ?? '') };
    if (!isConstant(row.value) || row.source === '') continue;
    out[factKey(row.name)] = { value: row.value, source: row.source };
  }

  if (Object.keys(out).length === 0) {
    throw new Error('FACT-SHEET parsed to zero constants — refusing to verify against nothing');
  }
  return out;
}

/**
 * Read the sheet from `TASKLY_FACT_SHEET`.
 *
 * No default path. A guessed one that happens to be wrong on a deploy fails in
 * exactly the way this module exists to prevent: quietly, with a gate that
 * still reports passing.
 */
export const FACT_SHEET_ENV = 'TASKLY_FACT_SHEET';

export function loadFactSheet(env: NodeJS.ProcessEnv = process.env): FactSheet {
  const path = env[FACT_SHEET_ENV]?.trim();
  if (!path) {
    throw new Error(
      `${FACT_SHEET_ENV} is not set — it must point at taskly-brain/00-brain/FACT-SHEET.md ` +
        'in the marketplace repo. Verifying against no constants is not verifying.',
    );
  }
  return parseFactSheet(readFileSync(path, 'utf8'));
}
