/**
 * THE CONSOLE — TMOS with a face.
 *
 * Everything this system knows has, until now, been reachable only through a
 * CLI and a static HTML file regenerated by that CLI. That is enough to prove
 * the machinery works and not enough to USE: you cannot press a stage, you
 * cannot watch it run, and the page you read is always as old as the last time
 * someone remembered to run the worker.
 *
 * ── BOUND TO LOOPBACK, DELIBERATELY ────────────────────────────────────────
 *
 * This process holds a database connection with write access and can spawn the
 * worker. It listens on 127.0.0.1 ONLY — never 0.0.0.0 — because a server that
 * runs passes and reads the world model is not something to expose to a café
 * network by accident. There is no auth, and that is only acceptable because
 * nothing outside this machine can reach it.
 *
 * ── IT DOES NOT SCHEDULE ANYTHING ──────────────────────────────────────────
 *
 * The founder's call, and it matches what the worker already believed: a pass
 * runs when a human asks for one. `scripts/schedule.md` still documents launchd
 * for whoever wants it back; nothing here starts a timer.
 */
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { closePool } from '@tmos/db';
import { SEED_QUESTIONS, writePrediction, PredictionRejected } from '@tmos/intel';
import {
  NotFoundError,
  archiveThread,
  createPostgresPredictionStore,
  createResolverContext,
  deleteThread,
  getThread,
  listThreads,
  renameThread,
} from '@tmos/adapters';

import { readState } from './queries.js';
import { runResearch } from './research-route.js';
import { runDraft } from './draft-route.js';
import { runAnswer } from './answer-route.js';
import { primeBudget } from './budget-boot.js';
import { Runner, RunBusy, isStage } from './runner.js';

/** dist/ sits one level under the app, so the repo root is three up. */
const HERE = dirname(fileURLToPath(import.meta.url));
const APP_ROOT = resolve(HERE, '..');
const REPO_ROOT = resolve(APP_ROOT, '../..');
const UI = resolve(APP_ROOT, 'src/ui.html');
/** The answer engine. `/` since 2026-08-31; the dashboard moved to /classic. */
const APP = resolve(APP_ROOT, 'src/app.html');

const HUMAN_AUTHOR = 'human:nishant';
const runner = new Runner(REPO_ROOT);

const json = (res: ServerResponse, code: number, body: unknown): void => {
  const s = JSON.stringify(body);
  res.writeHead(code, { 'content-type': 'application/json', 'content-length': Buffer.byteLength(s) });
  res.end(s);
};
const text = (res: ServerResponse, code: number, body: string): void => {
  res.writeHead(code, { 'content-type': 'text/plain; charset=utf-8' });
  res.end(body);
};

async function readBody(req: IncomingMessage): Promise<Record<string, unknown>> {
  const chunks: Buffer[] = [];
  let size = 0;
  for await (const c of req) {
    size += (c as Buffer).length;
    // A console form posts a few hundred bytes. Anything larger is a mistake or
    // a probe, and reading it into memory unbounded is the mistake to avoid.
    if (size > 64_000) throw new Error('body too large');
    chunks.push(c as Buffer);
  }
  if (chunks.length === 0) return {};
  const parsed: unknown = JSON.parse(Buffer.concat(chunks).toString('utf8'));
  return typeof parsed === 'object' && parsed !== null ? (parsed as Record<string, unknown>) : {};
}

/**
 * Stream a run to the browser.
 *
 * The backlog is replayed before subscribing, so a tab opened mid-pass — or
 * reloaded — sees the whole run rather than joining halfway with no context.
 */
function stream(res: ServerResponse): void {
  const handle = runner.last();
  res.writeHead(200, {
    'content-type': 'text/event-stream',
    'cache-control': 'no-cache',
    connection: 'keep-alive',
  });
  if (!handle) {
    res.write(`event: end\ndata: 0\n\n`);
    res.end();
    return;
  }
  for (const line of handle.lines) res.write(`event: line\ndata: ${JSON.stringify(line)}\n\n`);
  if (handle.finished) {
    res.write(`event: end\ndata: ${JSON.stringify(handle.exitCode ?? 0)}\n\n`);
    res.end();
    return;
  }
  const onLine = (l: string): void => {
    res.write(`event: line\ndata: ${JSON.stringify(l)}\n\n`);
  };
  const onEnd = (code: number | null): void => {
    res.write(`event: end\ndata: ${JSON.stringify(code ?? 0)}\n\n`);
    res.end();
  };
  handle.events.on('line', onLine);
  handle.events.once('end', onEnd);
  // Without this a closed tab leaks a listener per reload, and a pass emitting
  // hundreds of lines then writes to dead sockets.
  res.on('close', () => {
    handle.events.off('line', onLine);
    handle.events.off('end', onEnd);
  });
}

async function forecast(res: ServerResponse, body: Record<string, unknown>): Promise<void> {
  const key = String(body['key'] ?? '');
  const raw = String(body['p'] ?? '');
  const because = String(body['because'] ?? '').trim();

  const q = SEED_QUESTIONS.find((x) => x.key === key);
  if (!q) return text(res, 400, `unknown question "${key}"`);
  if (because === '') {
    return text(res, 400, 'a reason is required — a forecast with no reasoning teaches nothing when it resolves');
  }

  const n = Number(raw);
  if (!Number.isFinite(n)) return text(res, 400, `"${raw}" is not a number — give a probability like 0.7`);
  if (n > 1) {
    return text(res, 400, `"${raw}" looks like a percentage — give ${n / 100}, not ${n}`);
  }
  if (n < 0.01 || n > 0.99) {
    return text(res, 400, `"${raw}" must be between 0.01 and 0.99 — a forecast that cannot be wrong is not a forecast`);
  }

  const store = createPostgresPredictionStore();
  const already = (await store.all()).some(
    (r) => r.author === HUMAN_AUTHOR && r.claim === q.claim,
  );
  if (already) {
    return text(res, 409, 'you have already forecast this one — a second row double-counts in every score it touches');
  }

  try {
    await writePrediction(
      store,
      {
        claim: q.claim,
        p: n,
        author: HUMAN_AUTHOR,
        resolve_at: q.resolve_at,
        resolver: q.resolver,
        evidence: { key: q.key, rationale: q.rationale, because },
      },
      createResolverContext(),
    );
  } catch (err) {
    const msg = err instanceof PredictionRejected ? err.message : String(err);
    return text(res, 400, `refused: ${msg}`);
  }
  return text(res, 200, `Recorded — ${q.key} at ${n}. It resolves on ${q.resolve_at.slice(0, 10)}.`);
}

/**
 * `/api/threads/<uuid>` and its two verbs.
 *
 * The id is matched as a UUID rather than as `[^/]+` so a path that is not one
 * is a 404 here instead of a `22P02` from Postgres several layers down — the
 * store refuses a non-uuid anyway, but a route that hands the database
 * arbitrary path segments is the shape to avoid whether or not it is safe today.
 */
const THREAD_PATH = /^\/api\/threads\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:\/(rename|archive))?$/i;

async function threadRoute(
  req: IncomingMessage,
  res: ServerResponse,
  id: string,
  action: string | null,
): Promise<void> {
  const method = req.method ?? 'GET';
  try {
    if (action === null && method === 'GET') {
      const detail = await getThread(id);
      return detail === null ? text(res, 404, `unknown thread: ${id}`) : json(res, 200, detail);
    }
    if (action === null && method === 'DELETE') {
      // Hard delete, cascading to messages and citations. `ai_usage_log` is
      // untouched on purpose: the spend happened, and a ledger that shrinks
      // when someone tidies up is not a ledger.
      await deleteThread(id);
      return json(res, 200, { deleted: id });
    }
    if (action === 'rename' && method === 'POST') {
      const title = String((await readBody(req))['title'] ?? '').trim();
      if (title === '') return text(res, 400, 'a title is required — a blank one is refused by the store');
      // A rename also stamps `title_source = 'user'`, which is what stops a
      // later auto-titler from overwriting it.
      await renameThread(id, title);
      return json(res, 200, { id, title });
    }
    if (action === 'archive' && method === 'POST') {
      // Soft delete, and undoable: `{"archived": false}` puts it back. That
      // reversibility is the whole difference from DELETE.
      const archived = (await readBody(req))['archived'] !== false;
      await archiveThread(id, archived ? new Date().toISOString() : null);
      return json(res, 200, { id, archived });
    }
  } catch (err) {
    if (err instanceof NotFoundError) return text(res, 404, err.message);
    throw err;
  }
  return text(res, 405, `${method} is not allowed on ${threadPath(id, action)}`);
}

const threadPath = (id: string, action: string | null): string =>
  action === null ? `/api/threads/${id}` : `/api/threads/${id}/${action}`;

async function route(req: IncomingMessage, res: ServerResponse): Promise<void> {
  const url = new URL(req.url ?? '/', 'http://localhost');
  const path = url.pathname;

  if (path === '/' || path === '/index.html') {
    // The answer engine is the front door now. Read per request rather than at
    // boot so editing the page and hitting reload shows the edit — which is the
    // whole reason it is a file and not a template string.
    res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
    res.end(readFileSync(APP, 'utf8'));
    return;
  }

  /**
   * The old dashboard, kept whole rather than ported.
   *
   * It carries five tabs the answer engine does not replace — findings, the
   * competitor fact table, the forecast ledger and its write form, sources, and
   * the stage runner. Deleting it to look tidy would delete working surfaces,
   * so it stays here until each has a home in the new shell.
   */
  if (path === '/classic') {
    // Read per request rather than at boot: editing the page and hitting
    // reload should show the edit, which is the whole point of it being a file.
    const html = readFileSync(UI, 'utf8');
    res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
    res.end(html);
    return;
  }

  if (path === '/api/state') return json(res, 200, await readState());

  if (path === '/api/questions') {
    const rows = await createPostgresPredictionStore().all();
    return json(
      res,
      200,
      SEED_QUESTIONS.map((q) => {
        const ours = rows.find((r) => r.author === HUMAN_AUTHOR && r.claim === q.claim);
        return {
          key: q.key,
          claim: q.claim,
          resolve_at: q.resolve_at,
          yours: ours?.p ?? null,
          // The agent's number is withheld until yours exists. See forecast.ts:
          // reading it first makes your forecast a copy, and two correlated
          // numbers cannot be scored against each other.
          agent: ours ? (rows.find((r) => r.author.startsWith('agent:') && r.claim === q.claim)?.p ?? null) : null,
        };
      }),
    );
  }

  if (path === '/api/status') {
    const h = runner.last();
    return json(res, 200, {
      running: runner.active() !== null,
      stage: h?.stage ?? null,
      lines: h?.lines ?? [],
    });
  }

  if (path === '/api/stream') return stream(res);

  if (path === '/api/draft') return runDraft(res);

  if (path === '/api/research') {
    // GET, because EventSource cannot POST. The question rides in the query
    // string and is never logged anywhere a URL would be.
    return runResearch(res, url.searchParams.get('q') ?? '');
  }

  if (path === '/api/answer') {
    // GET, because EventSource cannot POST. `thread` continues a conversation;
    // its absence starts one.
    return runAnswer(res, url.searchParams.get('q') ?? '', url.searchParams.get('thread'));
  }

  if (path === '/api/threads' && (req.method ?? 'GET') === 'GET') {
    // Archived threads are excluded by default, and asking for them changes the
    // SQL rather than a parameter — `thread_active_idx` is partial, and the
    // planner only uses it when the predicate is written literally.
    const includeArchived = url.searchParams.get('archived') === '1';
    return json(res, 200, await listThreads({ includeArchived }));
  }

  const thread = THREAD_PATH.exec(path);
  if (thread) {
    return threadRoute(req, res, thread[1] ?? '', thread[2] ?? null);
  }

  if (path === '/api/run' && req.method === 'POST') {
    const body = await readBody(req);
    const stage = String(body['stage'] ?? 'all');
    if (!isStage(stage)) return text(res, 400, `unknown stage "${stage}"`);
    try {
      runner.start(stage, body['free'] === true);
      return json(res, 202, { started: stage });
    } catch (err) {
      if (err instanceof RunBusy) return text(res, 409, err.message);
      throw err;
    }
  }

  if (path === '/api/stop' && req.method === 'POST') {
    return json(res, 200, { stopped: runner.stop() });
  }

  if (path === '/api/forecast' && req.method === 'POST') {
    return forecast(res, await readBody(req));
  }

  return text(res, 404, 'not found');
}

const server = createServer((req, res) => {
  route(req, res).catch((err: unknown) => {
    const msg = err instanceof Error ? err.message : String(err);
    if (!res.headersSent) text(res, 500, msg);
    else res.end();
  });
});

const PORT = Number(process.env['TMOS_CONSOLE_PORT'] ?? 4478);
server.listen(PORT, '127.0.0.1', () => {
  console.log(`\n  TMOS console → http://127.0.0.1:${PORT}\n`);
  console.log('  Nothing is scheduled. A pass runs when you press one.\n');
  /**
   * REBUILD THE DAY'S SPEND BEFORE THE FIRST QUESTION.
   *
   * `BudgetState` is in-memory and per-process, so the $20/day ceiling has
   * until now reset on every restart — migration 012 created `ai_usage_log`
   * for exactly this and wrote the query into its own table comment, and
   * nothing ever ran it. Done here rather than lazily so the founder does not
   * wait for the read mid-answer; `dailyBudget()` reconstructs anyway if this
   * could not, so a database that is not up yet costs a warning, not a boot.
   */
  void primeBudget().catch((err: unknown) => {
    const why = err instanceof Error ? err.message : String(err);
    console.error(`budget: could not reconstruct today's spend at boot (${why})`);
  });
});

const shutdown = (): void => {
  server.close();
  void closePool().finally(() => process.exit(0));
};
process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
