/**
 * THE CONSOLE — TMOS with a face.
 *
 * Everything this system knows has, until now, been reachable only through a
 * CLI and a static HTML file regenerated by that CLI. That is enough to prove
 * the machinery works and not enough to USE: you cannot press a stage, you
 * cannot watch it run, and the page you read is always as old as the last time
 * someone remembered to run the worker.
 *
 * ── BOUND TO LOOPBACK, DELIBERATELY ────────────────────────────────────────
 *
 * This process holds a database connection with write access and can spawn the
 * worker. It listens on 127.0.0.1 ONLY — never 0.0.0.0 — because a server that
 * runs passes and reads the world model is not something to expose to a café
 * network by accident. There is no auth, and that is only acceptable because
 * nothing outside this machine can reach it.
 *
 * ── IT DOES NOT SCHEDULE ANYTHING ──────────────────────────────────────────
 *
 * The founder's call, and it matches what the worker already believed: a pass
 * runs when a human asks for one. `scripts/schedule.md` still documents launchd
 * for whoever wants it back; nothing here starts a timer.
 */
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { closePool } from '@tmos/db';
import { SEED_QUESTIONS, writePrediction, PredictionRejected } from '@tmos/intel';
import { createPostgresPredictionStore, createResolverContext } from '@tmos/adapters';

import { readState } from './queries.js';
import { runResearch } from './research-route.js';
import { runDraft } from './draft-route.js';
import { Runner, RunBusy, isStage } from './runner.js';

/** dist/ sits one level under the app, so the repo root is three up. */
const HERE = dirname(fileURLToPath(import.meta.url));
const APP_ROOT = resolve(HERE, '..');
const REPO_ROOT = resolve(APP_ROOT, '../..');
const UI = resolve(APP_ROOT, 'src/ui.html');

const HUMAN_AUTHOR = 'human:nishant';
const runner = new Runner(REPO_ROOT);

const json = (res: ServerResponse, code: number, body: unknown): void => {
  const s = JSON.stringify(body);
  res.writeHead(code, { 'content-type': 'application/json', 'content-length': Buffer.byteLength(s) });
  res.end(s);
};
const text = (res: ServerResponse, code: number, body: string): void => {
  res.writeHead(code, { 'content-type': 'text/plain; charset=utf-8' });
  res.end(body);
};

async function readBody(req: IncomingMessage): Promise<Record<string, unknown>> {
  const chunks: Buffer[] = [];
  let size = 0;
  for await (const c of req) {
    size += (c as Buffer).length;
    // A console form posts a few hundred bytes. Anything larger is a mistake or
    // a probe, and reading it into memory unbounded is the mistake to avoid.
    if (size > 64_000) throw new Error('body too large');
    chunks.push(c as Buffer);
  }
  if (chunks.length === 0) return {};
  const parsed: unknown = JSON.parse(Buffer.concat(chunks).toString('utf8'));
  return typeof parsed === 'object' && parsed !== null ? (parsed as Record<string, unknown>) : {};
}

/**
 * Stream a run to the browser.
 *
 * The backlog is replayed before subscribing, so a tab opened mid-pass — or
 * reloaded — sees the whole run rather than joining halfway with no context.
 */
function stream(res: ServerResponse): void {
  const handle = runner.last();
  res.writeHead(200, {
    'content-type': 'text/event-stream',
    'cache-control': 'no-cache',
    connection: 'keep-alive',
  });
  if (!handle) {
    res.write(`event: end\ndata: 0\n\n`);
    res.end();
    return;
  }
  for (const line of handle.lines) res.write(`event: line\ndata: ${JSON.stringify(line)}\n\n`);
  if (handle.finished) {
    res.write(`event: end\ndata: ${JSON.stringify(handle.exitCode ?? 0)}\n\n`);
    res.end();
    return;
  }
  const onLine = (l: string): void => {
    res.write(`event: line\ndata: ${JSON.stringify(l)}\n\n`);
  };
  const onEnd = (code: number | null): void => {
    res.write(`event: end\ndata: ${JSON.stringify(code ?? 0)}\n\n`);
    res.end();
  };
  handle.events.on('line', onLine);
  handle.events.once('end', onEnd);
  // Without this a closed tab leaks a listener per reload, and a pass emitting
  // hundreds of lines then writes to dead sockets.
  res.on('close', () => {
    handle.events.off('line', onLine);
    handle.events.off('end', onEnd);
  });
}

async function forecast(res: ServerResponse, body: Record<string, unknown>): Promise<void> {
  const key = String(body['key'] ?? '');
  const raw = String(body['p'] ?? '');
  const because = String(body['because'] ?? '').trim();

  const q = SEED_QUESTIONS.find((x) => x.key === key);
  if (!q) return text(res, 400, `unknown question "${key}"`);
  if (because === '') {
    return text(res, 400, 'a reason is required — a forecast with no reasoning teaches nothing when it resolves');
  }

  const n = Number(raw);
  if (!Number.isFinite(n)) return text(res, 400, `"${raw}" is not a number — give a probability like 0.7`);
  if (n > 1) {
    return text(res, 400, `"${raw}" looks like a percentage — give ${n / 100}, not ${n}`);
  }
  if (n < 0.01 || n > 0.99) {
    return text(res, 400, `"${raw}" must be between 0.01 and 0.99 — a forecast that cannot be wrong is not a forecast`);
  }

  const store = createPostgresPredictionStore();
  const already = (await store.all()).some(
    (r) => r.author === HUMAN_AUTHOR && r.claim === q.claim,
  );
  if (already) {
    return text(res, 409, 'you have already forecast this one — a second row double-counts in every score it touches');
  }

  try {
    await writePrediction(
      store,
      {
        claim: q.claim,
        p: n,
        author: HUMAN_AUTHOR,
        resolve_at: q.resolve_at,
        resolver: q.resolver,
        evidence: { key: q.key, rationale: q.rationale, because },
      },
      createResolverContext(),
    );
  } catch (err) {
    const msg = err instanceof PredictionRejected ? err.message : String(err);
    return text(res, 400, `refused: ${msg}`);
  }
  return text(res, 200, `Recorded — ${q.key} at ${n}. It resolves on ${q.resolve_at.slice(0, 10)}.`);
}

async function route(req: IncomingMessage, res: ServerResponse): Promise<void> {
  const url = new URL(req.url ?? '/', 'http://localhost');
  const path = url.pathname;

  if (path === '/' || path === '/index.html') {
    // Read per request rather than at boot: editing the page and hitting
    // reload should show the edit, which is the whole point of it being a file.
    const html = readFileSync(UI, 'utf8');
    res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
    res.end(html);
    return;
  }

  if (path === '/api/state') return json(res, 200, await readState());

  if (path === '/api/questions') {
    const rows = await createPostgresPredictionStore().all();
    return json(
      res,
      200,
      SEED_QUESTIONS.map((q) => {
        const ours = rows.find((r) => r.author === HUMAN_AUTHOR && r.claim === q.claim);
        return {
          key: q.key,
          claim: q.claim,
          resolve_at: q.resolve_at,
          yours: ours?.p ?? null,
          // The agent's number is withheld until yours exists. See forecast.ts:
          // reading it first makes your forecast a copy, and two correlated
          // numbers cannot be scored against each other.
          agent: ours ? (rows.find((r) => r.author.startsWith('agent:') && r.claim === q.claim)?.p ?? null) : null,
        };
      }),
    );
  }

  if (path === '/api/status') {
    const h = runner.last();
    return json(res, 200, {
      running: runner.active() !== null,
      stage: h?.stage ?? null,
      lines: h?.lines ?? [],
    });
  }

  if (path === '/api/stream') return stream(res);

  if (path === '/api/draft') return runDraft(res);

  if (path === '/api/research') {
    // GET, because EventSource cannot POST. The question rides in the query
    // string and is never logged anywhere a URL would be.
    return runResearch(res, url.searchParams.get('q') ?? '');
  }

  if (path === '/api/run' && req.method === 'POST') {
    const body = await readBody(req);
    const stage = String(body['stage'] ?? 'all');
    if (!isStage(stage)) return text(res, 400, `unknown stage "${stage}"`);
    try {
      runner.start(stage, body['free'] === true);
      return json(res, 202, { started: stage });
    } catch (err) {
      if (err instanceof RunBusy) return text(res, 409, err.message);
      throw err;
    }
  }

  if (path === '/api/stop' && req.method === 'POST') {
    return json(res, 200, { stopped: runner.stop() });
  }

  if (path === '/api/forecast' && req.method === 'POST') {
    return forecast(res, await readBody(req));
  }

  return text(res, 404, 'not found');
}

const server = createServer((req, res) => {
  route(req, res).catch((err: unknown) => {
    const msg = err instanceof Error ? err.message : String(err);
    if (!res.headersSent) text(res, 500, msg);
    else res.end();
  });
});

const PORT = Number(process.env['TMOS_CONSOLE_PORT'] ?? 4478);
server.listen(PORT, '127.0.0.1', () => {
  console.log(`\n  TMOS console → http://127.0.0.1:${PORT}\n`);
  console.log('  Nothing is scheduled. A pass runs when you press one.\n');
});

const shutdown = (): void => {
  server.close();
  void closePool().finally(() => process.exit(0));
};
process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
