import { describe, it, expect } from 'vitest';
import {
  checkFactSheet,
  checkIndependence,
  parseGeneratedBy,
  passesVerification,
  verifyAdversarially,
  REFUTE_INSTRUCTION,
} from './adversarial.js';
import type {
  FactSheet,
  ModelIdentity,
  RefutationRequest,
  RefutationResponse,
  VerifiableFinding,
  VerifierPort,
} from './adversarial.js';

const URL = 'https://jiffyondemand.com/pricing';
const WRITER = 'agent:groq/llama-3.3-70b@2026-05-01';
const OBSERVED_AT = '2026-08-04T00:00:00.000Z';

/**
 * The real numbers, read from
 * `taskly-brain/00-brain/FACT-SHEET.md` (generated by `npm run brain:facts`
 * from `lib/marketplace/fees.ts`). Injected, never hardcoded in the verifier —
 * a second copy of a constant is a second thing that can go stale.
 */
const FACTS: FactSheet = {
  tasker_commission: {
    value: '20%',
    source: 'lib/marketplace/fees.ts',
    subject: ['commission', 'take rate', 'taskly takes', 'tasker-side cut'],
  },
  poster_platform_fee_rate: {
    value: '4.9%',
    source: 'lib/marketplace/fees.ts',
    subject: ['platform fee', 'poster fee'],
  },
  poster_platform_fee_floor: {
    value: '$2.99',
    source: 'lib/marketplace/fees.ts',
    subject: ['fee floor', 'minimum fee'],
  },
  urgent_boost: { value: '$5.00', source: 'lib/marketplace/fees.ts', subject: ['urgent boost'] },
  hst_rate: { value: '13%', source: 'lib/marketplace/fees.ts', subject: ['hst'] },
};

/** A port that records what it was asked, so a test can assert it was NOT. */
class SpyVerifier implements VerifierPort {
  readonly calls: RefutationRequest[] = [];
  constructor(
    readonly identity: ModelIdentity,
    private readonly reply: RefutationResponse | Error = {
      verdict: 'survives',
      reason: 'the span says exactly this',
      span: null,
    },
  ) {}
  async refute(request: RefutationRequest): Promise<RefutationResponse> {
    this.calls.push(request);
    if (this.reply instanceof Error) throw this.reply;
    return this.reply;
  }
}

const OTHER: ModelIdentity = { model: 'anthropic/claude-opus-4', version: '2026-06-01' };
const SAME: ModelIdentity = { model: 'groq/llama-3.3-70b', version: '2026-05-01' };

const finding = (claim: string, spans: string[] = [claim]): VerifiableFinding => ({
  claim,
  evidence: spans.map((span) => ({ source_url: URL, span, observed_at: OBSERVED_AT })),
  generated_by: WRITER,
});

const verify = (f: VerifiableFinding, port: VerifierPort, facts: FactSheet = FACTS) =>
  verifyAdversarially(f, { verifier: port, retrievedUrls: [URL], facts });

/* ────────────────────────────────────────────────────────────────────────── */

describe('a model must not check its own work', () => {
  it('REFUSES when the verifying model is the generating model', async () => {
    const port = new SpyVerifier(SAME);
    const out = await verify(finding('Jiffy raised prices 12%.'), port);

    expect(out.verdict).not.toBe('survives');
    expect(passesVerification(out)).toBe(false);
    expect(out.stage).toBe('independence');
    expect(out.needs_human).toBe(true);
    expect(out.reason).toContain('groq/llama-3.3-70b');
    // The point of the refusal: no call is made at all.
    expect(port.calls).toHaveLength(0);
  });

  it('refuses even when only the version differs — same weights, same blind spots', async () => {
    const port = new SpyVerifier({ model: 'groq/llama-3.3-70b', version: '2026-09-09' });
    const out = await verify(finding('Jiffy raised prices 12%.'), port);
    expect(out.stage).toBe('independence');
    expect(port.calls).toHaveLength(0);
  });

  it('runs when the verifying model is genuinely a different one', async () => {
    const port = new SpyVerifier(OTHER);
    const out = await verify(finding('Jiffy raised prices 12%.'), port);
    expect(out.verdict).toBe('survives');
    expect(port.calls).toHaveLength(1);
  });

  it('fails closed on a generated_by it cannot parse', async () => {
    const port = new SpyVerifier(OTHER);
    const out = await verify({ ...finding('Prices rose 12%.'), generated_by: 'mystery' }, port);
    expect(out.stage).toBe('independence');
    expect(port.calls).toHaveLength(0);
  });

  it('allows a human-authored finding — there is no model to collude with', () => {
    expect(checkIndependence(OTHER, 'human:nishant').independent).toBe(true);
    expect(parseGeneratedBy(WRITER)).toEqual({
      model: 'groq/llama-3.3-70b',
      version: '2026-05-01',
    });
    expect(parseGeneratedBy('human:nishant')).toBeNull();
  });
});

describe('the FACT-SHEET checklist', () => {
  it('catches a claim contradicting the 20% commission', async () => {
    const port = new SpyVerifier(OTHER);
    const f = finding('Taskly takes 25% of every completed job.', [
      'Taskly takes 25% of every completed job.',
    ]);
    const out = await verify(f, port);

    expect(out.verdict).toBe('refuted');
    expect(out.stage).toBe('fact_sheet');
    expect(out.reason).toContain('20%');
    expect(out.reason).toContain('25%');
    expect(out.reason).toContain('lib/marketplace/fees.ts');
    // Deterministic and free — no reason to pay a model for it.
    expect(port.calls).toHaveLength(0);
  });

  it('lets the right number through', () => {
    expect(checkFactSheet('Taskly takes 20% of the deal.', FACTS)).toEqual([]);
  });

  it('does not fire when the correct value is also present in the sentence', () => {
    expect(checkFactSheet('Taskly takes 20%, and the poster platform fee is 4.9%.', FACTS)).toEqual(
      [],
    );
  });

  it('catches the poster fee floor and the fee rate', () => {
    const floor = checkFactSheet('The minimum fee is $3.99 per hire.', FACTS);
    expect(floor[0]).toMatchObject({ fact: 'poster_platform_fee_floor', expected: '$2.99' });

    const rate = checkFactSheet('The platform fee is 5.9% of the deal.', FACTS);
    expect(rate[0]).toMatchObject({ fact: 'poster_platform_fee_rate', found: '5.9%' });
  });

  it('catches a wrong urgent boost and a wrong HST rate', () => {
    expect(checkFactSheet('The urgent boost costs $9.', FACTS)[0]?.expected).toBe('$5.00');
    expect(checkFactSheet('HST is charged at 15%.', FACTS)[0]?.expected).toBe('13%');
  });

  it('compares like with like — a dollar figure never contradicts a percentage', () => {
    expect(checkFactSheet('Taskly takes 20% on a $250 commission-bearing job.', FACTS)).toEqual([]);
  });

  it('only looks at the sentence naming the subject', () => {
    // 25% is about ratings here, not about the take rate.
    expect(checkFactSheet('Taskly takes 20%. Ratings rose 25% last quarter.', FACTS)).toEqual([]);
  });

  it('derives subject words from the key when none are given', () => {
    const facts: FactSheet = { commission: { value: '20%', source: 'fees.ts' } };
    expect(checkFactSheet('The commission is 30%.', facts)).toHaveLength(1);
  });
});

describe('L0 runs first, and stops everything', () => {
  it('short-circuits a fabricated number before any model is asked', async () => {
    const port = new SpyVerifier(OTHER);
    const out = await verify(
      finding('Jiffy raised prices 23%.', ['Jiffy raised prices 12%.']),
      port,
    );

    expect(out.verdict).toBe('refuted');
    expect(out.stage).toBe('l0');
    expect(out.reason).toContain('23%');
    expect(port.calls).toHaveLength(0);
  });

  it('short-circuits a claim with no retrieved source', async () => {
    const port = new SpyVerifier(OTHER);
    const out = await verifyAdversarially(finding('Prices rose.'), {
      verifier: port,
      retrievedUrls: [],
      facts: FACTS,
    });
    expect(out.stage).toBe('l0');
    expect(port.calls).toHaveLength(0);
  });
});

describe('uncertain is not a pass', () => {
  const cases: Array<[string, RefutationResponse | Error]> = [
    ['the model says so outright', { verdict: 'uncertain', reason: 'cannot tell', span: null }],
    ['the verdict is not one we recognise', { verdict: 'probably ok', reason: 'sure', span: null }],
    ['the reason is empty', { verdict: 'survives', reason: '   ', span: null }],
    [
      'the model cites a span that was never sent',
      { verdict: 'refuted', reason: 'contradicted', span: 'a span nobody supplied' },
    ],
    ['the call throws', new Error('gateway timeout')],
  ];

  for (const [label, reply] of cases) {
    it(`abstains and demands a human when ${label}`, async () => {
      const port = new SpyVerifier(OTHER, reply);
      const out = await verify(finding('Jiffy raised prices 12%.'), port);
      expect(out.verdict).toBe('uncertain');
      expect(passesVerification(out)).toBe(false);
      expect(out.needs_human).toBe(true);
    });
  }

  it('a clean refutation does not need a human — it is already actionable', async () => {
    const span = 'Jiffy raised prices 12%.';
    const port = new SpyVerifier(OTHER, {
      verdict: 'refuted',
      reason: 'the span is about a different quarter',
      span,
    });
    const out = await verify(finding('Jiffy raised prices 12%.', [span]), port);
    expect(out.verdict).toBe('refuted');
    expect(out.span).toBe(span);
    expect(out.needs_human).toBe(false);
  });
});

describe('the prompt is built to refute, not to rate', () => {
  it('sends the refutation task, the cited spans only, and the constants', async () => {
    const port = new SpyVerifier(OTHER);
    await verify(finding('Jiffy raised prices 12%.', ['Jiffy raised prices 12%.']), port);

    const req = port.calls[0]!;
    expect(req.task).toBe('refute');
    expect(req.default_on_uncertainty).toBe('refuted');
    expect(req.instruction).toBe(REFUTE_INSTRUCTION);
    expect(req.spans).toEqual(['Jiffy raised prices 12%.']);
    expect(req.constants).toEqual(
      expect.arrayContaining([
        { name: 'tasker_commission', value: '20%', source: 'lib/marketplace/fees.ts' },
      ]),
    );
  });

  it('records which verifier produced the verdict', async () => {
    const port = new SpyVerifier(OTHER);
    const out = await verify(finding('Jiffy raised prices 12%.'), port);
    expect(out.verifier).toEqual(OTHER);
  });
});
